### ISSUE TITLE
Sir Rebral Option?

### ISSUE THREAD

**Issue by skang99** [alex-macm/Nature-Runecrafting-Util#1]
![image](https://github.com/user-attachments/assets/c07c5d5c-19e5-4baf-8935-290956743304)

On a PvP world, the Sir Rebral diary cape teleport (option 3) is 0-1 tiles away from the castle bank chest only found on PvP worlds. The highlighted tiles are all of the possible landing tiles. 

Would it be possible to add a configuration option for left click to be swapped to Sir Rebral rather than Jarr?

**Comment by alex-macm** [comment]
Added in latest update
