### ISSUE TITLE
Doesn't swap leftclick to Jarr

### ISSUE THREAD

**Issue by ghost** [alex-macm/Nature-Runecrafting-Util#2]
It doesn't swap the left click option to Jarr anymore after today's update (14-06-2024)

**Comment by Zelom37** [comment]
Seconded.

**Comment by mhmohyea** [comment]
+1 not working for me either

**Comment by AaronIsFab** [comment]
> +1 not working for me either

The PR completely fixes, just need to wait for the plugin author (@alex-macm) to merge it.
It actually changes the visible words too which current version never did for me

**Comment by yahia-h-ai** [comment]
> > +1 not working for me either
> 
> The PR completely fixes, just need to wait for the plugin author (@alex-macm) to merge it. It actually changes the visible words too which current version never did for me

@alex-macm is MIA it seems

**Comment by halo145** [comment]
Not fixed yet (19 Aug 2024)

**Comment by Zelom37** [comment]
Yes, still not resolved.  Even tried uninstalling and reinstalling the plugin to see if that would do it.  No dice.
