### ISSUE TITLE
Left click will not teleport to Jarr

### ISSUE THREAD

**Issue by halo145** [alex-macm/Nature-Runecrafting-Util#4]
I have left click diary cape teleport set to Kaleb and have the plugin turned on. When at the nature altar, left click tele will just send me back to Kaleb. Help please thanks

**Comment by alex-macm** [comment]
Wait for RL reveiwers to push the update live

https://github.com/runelite/plugin-hub/pull/6487

**Comment by alex-macm** [comment]
Check the following: 
> Menu entry swapper -> item swaps -> teleport submenus ticked ON 
> nature runecraft utilies ricked ON 
> left click entry for diary cape set to kaleb 

Answer the following: 
What is the left click option outside the nature altar 
what is the left click option inside the nature altar 
is your diary cape (t) or not
does ticking the sir rebral option in the plugin config send you to sir rebral

**Comment by BlitzAceSamy** [comment]
Is this supposed to only work in the inventory and not in equipment? It swaps my default left-click to Jarr when cape is in inventory (even though my default left-click teleport in inventory is set to Flax keeper, and this behavior is consistent in both trim and untrim capes), but my default-left click in equipment remains as Kaleb. Thanks!

**Comment by FredP1** [comment]
> Is this supposed to only work in the inventory and not in equipment? 

Yes, it's only set up to work with the cape in the inventory. I could take a look at getting it to work from the equipment tab if there's enough interest but from personal use, I just store it in the inventory for less clicks.

**Comment by alex-macm** [comment]
> Is this supposed to only work in the inventory and not in equipment? It swaps my default left-click to Jarr when cape is in inventory (even though my default left-click teleport in inventory is set to Flax keeper, and this behavior is consistent in both trim and untrim capes), but my default-left click in equipment remains as Kaleb. Thanks!

If you fork the plugin and code it yourself I can add it. But I just keep the cape in my inventory.
